# Generated by .github/workflows/release.yml on every tagged release.
# Edits here are overwritten; change the workflow instead.
class Lagerregal < Formula
  desc "Classify and browse your installed Homebrew packages by category"
  homepage "https://github.com/admonstrator/homebrew-lagerregal"
  version "0.3.0"
  license "MIT"

  if Hardware::CPU.arm?
    url "https://github.com/admonstrator/homebrew-lagerregal/releases/download/v0.3.0/lagerregal-0.3.0-aarch64-apple-darwin.tar.gz"
    sha256 "bda21e91dfcbd4caf7406bc4464bf20d51a72b09e14430ea55e057b8f712292c"
  else
    url "https://github.com/admonstrator/homebrew-lagerregal/releases/download/v0.3.0/lagerregal-0.3.0-x86_64-apple-darwin.tar.gz"
    sha256 "b95412736cd582b6748bae8e4ff7c403d4f4bbd3d9ee9a972ca32fb8e6fed756"
  end

  depends_on :macos

  def install
    bin.install "lagerregal"
  end

  test do
    assert_match "lagerregal", shell_output("#{bin}/lagerregal --version")
  end
end
