# Generated by .github/workflows/release.yml on every tagged release.
# Edits here are overwritten; change the workflow instead.
class Lagerregal < Formula
  desc "Classify and browse your installed Homebrew packages by category"
  homepage "https://github.com/admonstrator/homebrew-lagerregal"
  version "0.1.0"
  license "MIT"

  if Hardware::CPU.arm?
    url "https://github.com/admonstrator/homebrew-lagerregal/releases/download/v0.1.0/lagerregal-0.1.0-aarch64-apple-darwin.tar.gz"
    sha256 "6ac3d8a1e6407e229ea73a641d8a34430f13b89bd26c259275299b74c798ea62"
  else
    url "https://github.com/admonstrator/homebrew-lagerregal/releases/download/v0.1.0/lagerregal-0.1.0-x86_64-apple-darwin.tar.gz"
    sha256 "b1c4f83bea8e77a6b3b34ad64e81789e5601bee63932433d4904bc756efc375b"
  end

  depends_on :macos

  def install
    bin.install "lagerregal"
  end

  test do
    assert_match "lagerregal", shell_output("#{bin}/lagerregal --version")
  end
end
