# Generated by .github/workflows/release.yml on every tagged release.
# Edits here are overwritten; change the workflow instead.
class Lagerregal < Formula
  desc "Classify and browse your installed Homebrew packages by category"
  homepage "https://github.com/admonstrator/homebrew-lagerregal"
  version "0.2.0"
  license "MIT"

  if Hardware::CPU.arm?
    url "https://github.com/admonstrator/homebrew-lagerregal/releases/download/v0.2.0/lagerregal-0.2.0-aarch64-apple-darwin.tar.gz"
    sha256 "b24b3bc5db4fa6f7e20c4fc06c2c11b8ba12ee51dd73fe589f7f8fb1dbfd970a"
  else
    url "https://github.com/admonstrator/homebrew-lagerregal/releases/download/v0.2.0/lagerregal-0.2.0-x86_64-apple-darwin.tar.gz"
    sha256 "c3d6e90dc093cfd98c623be03585ffeac788aa7bbc00450d6aaecf2b6fe7a505"
  end

  depends_on :macos

  def install
    bin.install "lagerregal"
  end

  test do
    assert_match "lagerregal", shell_output("#{bin}/lagerregal --version")
  end
end
