#!/usr/bin/env bash
#
# Generate the Homebrew formula for the current release and push it to the
# owner's `homebrew-tap` repository. Run by .github/workflows/release.yml with:
#   GH_TAP_PAT  - a PAT with contents:write on <owner>/homebrew-tap
#   TAG         - the release tag (e.g. v0.5.0)
#   TAP_TAG     - the tag of the tap release holding this version's binaries
# and the release artifacts plus their .sha256 sidecars under ./dist/.
set -euo pipefail

TAG="${TAG:-${GITHUB_REF_NAME:?TAG or GITHUB_REF_NAME required}}"
VERSION="${TAG#v}"
OWNER="${GITHUB_REPOSITORY_OWNER:?}"
REPO="${GITHUB_REPOSITORY:?}" # owner/homebrew-lagerregal
TAP_REPO="homebrew-tap"
# Downloads come from the shared tap repo's releases, so everything installed
# from this tap is fetched from one public place regardless of where its source
# lives. Tap tags are project-prefixed because the tap carries releases for
# more than one project and a bare v* would collide.
TAP_TAG="${TAP_TAG:-lagerregal-${TAG}}"
BASE="https://github.com/${OWNER}/${TAP_REPO}/releases/download/${TAP_TAG}"
# Overridable so the clone/commit/push path can be exercised against a local
# repository without a token.
TAP_REMOTE="${TAP_REMOTE:-https://x-access-token:${GH_TAP_PAT:?}@github.com/${OWNER}/${TAP_REPO}.git}"

sha_for() {
  # Extract the hash from "<hash>  <filename>".
  awk '{print $1}' "dist/lagerregal-${VERSION}-$1.tar.gz.sha256"
}

SHA_MAC_ARM="$(sha_for aarch64-apple-darwin)"
SHA_MAC_X64="$(sha_for x86_64-apple-darwin)"
SHA_LINUX_ARM="$(sha_for aarch64-unknown-linux-musl)"
SHA_LINUX_X64="$(sha_for x86_64-unknown-linux-musl)"

echo "Formula for lagerregal ${VERSION} (binaries: ${TAP_TAG})"
echo "  macOS arm64 : ${SHA_MAC_ARM}"
echo "  macOS x86_64: ${SHA_MAC_X64}"
echo "  linux arm64 : ${SHA_LINUX_ARM}"
echo "  linux x86_64: ${SHA_LINUX_X64}"

# on_macos/on_linux plus on_arm/on_intel rather than Hardware::CPU.arm?, which
# would hand an ARM Linux host the macOS arm64 tarball.
cat > lagerregal.rb <<EOF
# Generated by the lagerregal release workflow — do not edit by hand.
class Lagerregal < Formula
  desc "Classify and browse your installed Homebrew packages by category"
  homepage "https://github.com/${REPO}"
  version "${VERSION}"
  license "MIT"

  on_macos do
    on_arm do
      url "${BASE}/lagerregal-${VERSION}-aarch64-apple-darwin.tar.gz"
      sha256 "${SHA_MAC_ARM}"
    end
    on_intel do
      url "${BASE}/lagerregal-${VERSION}-x86_64-apple-darwin.tar.gz"
      sha256 "${SHA_MAC_X64}"
    end
  end

  on_linux do
    on_arm do
      url "${BASE}/lagerregal-${VERSION}-aarch64-unknown-linux-musl.tar.gz"
      sha256 "${SHA_LINUX_ARM}"
    end
    on_intel do
      url "${BASE}/lagerregal-${VERSION}-x86_64-unknown-linux-musl.tar.gz"
      sha256 "${SHA_LINUX_X64}"
    end
  end

  def install
    bin.install "lagerregal"
  end

  test do
    assert_match "lagerregal", shell_output("#{bin}/lagerregal --version")
  end
end
EOF

rm -rf tap
git clone "${TAP_REMOTE}" tap
cd tap
if ! git rev-parse HEAD >/dev/null 2>&1; then
  # Empty tap repository: start its default branch.
  git checkout -b main
fi
mkdir -p Formula
cp ../lagerregal.rb Formula/lagerregal.rb
git add Formula/lagerregal.rb
if git diff --cached --quiet; then
  echo "Formula unchanged; nothing to push."
  exit 0
fi
git -c user.name="github-actions[bot]" \
    -c user.email="41898282+github-actions[bot]@users.noreply.github.com" \
    commit -m "lagerregal ${VERSION}"
git push -u origin HEAD
echo "Pushed lagerregal ${VERSION} to ${OWNER}/${TAP_REPO}."
